name: local_db
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  sqflite_sqlcipher: ^2.1.1+1
  movie:
    path: ../movie
  tv:
    path: ../tv
  core:
    path: ../core
  http: ^0.13.5
  readmore: ^2.2.0
  dartz: ^0.10.1
  flutter_rating_bar: ^4.0.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  rxdart: ^0.27.7
  cached_network_image: ^3.2.3
  eva_icons_flutter: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.3.3
  bloc_test: ^9.1.1

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
