// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWbeCHUdn6S0Yq3sSmNVMEyNrCm-kWrzM',
    appId: '1:116548330558:web:a2bc7a2d40a76047005d6f',
    messagingSenderId: '116548330558',
    projectId: 'tmdb-movies-app-cb67a',
    authDomain: 'tmdb-movies-app-cb67a.firebaseapp.com',
    databaseURL: 'https://tmdb-movies-app-cb67a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tmdb-movies-app-cb67a.appspot.com',
    measurementId: 'G-KT51KL0Y4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS63l3YBV_H3FZQryFQdR-URpZFm4SBS0',
    appId: '1:116548330558:android:a7fa7b282f377668005d6f',
    messagingSenderId: '116548330558',
    projectId: 'tmdb-movies-app-cb67a',
    databaseURL: 'https://tmdb-movies-app-cb67a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tmdb-movies-app-cb67a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfkQDMEqJtMhdyHO7XFNJKxBSPBKOdRwk',
    appId: '1:116548330558:ios:01492b79b54d47c9005d6f',
    messagingSenderId: '116548330558',
    projectId: 'tmdb-movies-app-cb67a',
    databaseURL: 'https://tmdb-movies-app-cb67a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tmdb-movies-app-cb67a.appspot.com',
    iosClientId: '116548330558-qraugheqheai2ergt75uftqfeo6kq55j.apps.googleusercontent.com',
    iosBundleId: 'com.example.tmdbMoviesApp',
  );
}
