name: movie
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_rating_bar: ^4.0.1
  http: ^0.13.5
  readmore: ^2.2.0
  rxdart: ^0.27.7
  core:
    path: ../core
  local_db:
    path: ../local_db
  watchlist:
    path: ../watchlist
  eva_icons_flutter: ^3.1.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mockito: ^5.4.0
  bloc_test: ^9.1.1

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
